export const menuItem = [
    {
        route:"/dashboard",
        text:"Dashboard",
    },
    {
        route:"/user",
        text:"Manage User",
    },
    {
        route:"/properties",
        text:"Manage Properties",
    },
    {
        route:"/appointment",
        text:"Manage Appointments",
    },
    {
        route:"/transaction",
        text:"Manage Transactions",
    }
]

export const userDummyData = [
  {
    id: "1",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "John Doe",
    email: "johndoe@gmail.com",
    phone: "1234567890",
    role: "Admin",
    status: "Active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
  },
  {
    id: "2",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Zaw Zaw",
    email: "zawzaw@gmail.com",
    phone: "0977777777",
    role: "Buyer",
    status: "Active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
  },
  {
    id: "3",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Aung Aung",
    email: "aungaung@gmail.com",
    phone: "0988888888",
    role: "Agent",
    license_number: "1234567890",
    agency_name: "Aung Aung Real Estate",
    experience_years: 5,
    bio: "Experienced real estate agent focusing on residential properties and investment consultations.",
    status: "Inactive",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
  },
  {
    id: "4",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Thida Win",
    email: "thidawin@gmail.com",
    phone: "0991234567",
    role: "Buyer",
    status: "Active",
    created_at: "2023-02-15",
    updated_at: "2023-02-15",
  },
  {
    id: "5",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Kyaw Kyaw",
    email: "kyawkyaw@gmail.com",
    phone: "0925001122",
    role: "Agent",
    license_number: "9876543210",
    agency_name: "Golden Home Realty",
    experience_years: 8,
    bio: "Specializing in luxury apartments and commercial real estate solutions.",
    status: "Active",
    created_at: "2023-03-10",
    updated_at: "2023-04-01",
  },
  {
    id: "6",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Sarah Smith",
    email: "sarah.smith@example.com",
    phone: "0945009988",
    role: "Admin",
    status: "Active",
    created_at: "2023-03-12",
    updated_at: "2023-03-12",
  },
  {
    id: "7",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Mya Mya",
    email: "myamya@gmail.com",
    phone: "0978112233",
    role: "Buyer",
    status: "Inactive",
    created_at: "2023-04-05",
    updated_at: "2023-04-05",
  },
  {
    id: "8",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Htin Lin",
    email: "htinlin@gmail.com",
    phone: "0995544332",
    role: "Agent",
    license_number: "4567891230",
    agency_name: "Apex Properties",
    experience_years: 3,
    bio: "Dedicated agent helping first-time buyers find their dream home effortless and smooth.",
    status: "Active",
    created_at: "2023-04-20",
    updated_at: "2023-05-10",
  },
  {
    id: "9",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Su Su",
    email: "susu@gmail.com",
    phone: "0969988776",
    role: "Buyer",
    status: "Inactive",
    created_at: "2023-05-01",
    updated_at: "2023-06-15",
  },
  {
    id: "10",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Michael Chen",
    email: "m.chen@example.com",
    phone: "0931223344",
    role: "Agent",
    license_number: "6543210987",
    agency_name: "Metropolis Realty Group",
    experience_years: 12,
    bio: "Senior real estate broker with over a decade of market analysis and property negotiation experience.",
    status: "Active",
    created_at: "2023-05-18",
    updated_at: "2023-05-18",
  },
  {
    id: "11",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Aye Aye Tint",
    email: "ayeaye.tint@gmail.com",
    phone: "0979887766",
    role: "Buyer",
    status: "Active",
    created_at: "2023-06-02",
    updated_at: "2023-06-02",
  },
  {
    id: "12",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Min Thant",
    email: "minthant@gmail.com",
    phone: "0942114455",
    role: "Agent",
    license_number: "3216549870",
    agency_name: "Urban Living Estate",
    experience_years: 2,
    bio: "Passionate about modern architectural homes and urban condominium rentals.",
    status: "Inactive",
    created_at: "2023-06-25",
    updated_at: "2023-06-25",
  },
  {
    id: "13",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Emma Watson",
    email: "emma.w@example.com",
    phone: "0989001122",
    role: "Admin",
    status: "Active",
    created_at: "2023-07-01",
    updated_at: "2023-07-01",
  },
  {
    id: "14",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Nanda Kyaw",
    email: "nandakyaw@gmail.com",
    phone: "0926778899",
    role: "Buyer",
    status: "Active",
    created_at: "2023-07-14",
    updated_at: "2023-07-20",
  },
  {
    id: "15",
    profileImage: "https://example.com/images/user1.jpg",
    full_name: "Khin Khaing",
    email: "khinkhaing@gmail.com",
    phone: "0996112233",
    role: "Agent",
    license_number: "7891234560",
    agency_name: "Prime Land & Homes",
    experience_years: 6,
    bio: "Focusing on suburban residential estates and long-term land investments.",
    status: "Active",
    created_at: "2023-08-01",
    updated_at: "2023-08-01",
  },
];

export const propertyDummyData = [
  {
    id: "1",
    title: "Luxury Apartment in Downtown",
    description: "A spacious 3-bedroom apartment with modern amenities and city views.",
    property_type: "Apartment",
    listing_type: "For Sale",
    price: 350000,
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1200,
    agentName: "Aung Aung",
    propertyImage: [
      {
        url: "https://example.com/images/property1.jpg",
        alt: "Luxury Apartment in Downtown",
      },
      {
        url: "https://example.com/images/property1_2.jpg",
        alt: "Living Room",
      },
      {
        url: "https://example.com/images/property1_3.jpg",
        alt: "Bedroom",
      },
    ],
    address: {
      street: "123 Main St",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11001",
      country: "Myanmar",
      latitude: 16.8409,
      longitude: 96.1735,
    },
    faviourite: [
      {
        userId: "2",
        created_at: "2023-01-20",
      },
      {
        userId: "5",
        created_at: "2023-02-15",
      },
    ],
    review: [
      {
        userId: "3",
        rating: 4,
        comment: "Great property with excellent amenities.",
        created_at: "2023-01-25",
        updated_at: "2023-01-25",
      },
      {
        userId: "6",
        rating: 5,
        comment: "Loved the location and the view from the apartment.",
        created_at: "2023-02-10",
        updated_at: "2023-02-10",
      },
    ],
    propertyView: [
      {
        userId: "4",
        ip_address: "192.168.1.1",
        viewed_at: "2023-01-30",
      },
      {
        userId: "7",
        ip_address: "192.168.1.2",
        viewed_at: "2023-02-01",
      },
    ],
    status: "Available",
    created_at: "2023-01-15",
    updated_at: "2023-01-15",
  },
  {
    id: "2",
    title: "Modern Condo Near Inya Lake",
    description: "Stylish 2-bedroom condominium with pool access and peaceful lake views.",
    property_type: "Condo",
    listing_type: "For Rent",
    price: 1500,
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 950,
    agentName: "Kyaw Kyaw",
    propertyImage: [
      {
        url: "https://example.com/images/property2_1.jpg",
        alt: "Condo Exterior",
      },
      {
        url: "https://example.com/images/property2_2.jpg",
        alt: "Balcony View",
      },
    ],
    address: {
      street: "45 Pyay Road",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11041",
      country: "Myanmar",
      latitude: 16.8322,
      longitude: 96.1458,
    },
    faviourite: [
      {
        userId: "4",
        created_at: "2023-03-01",
      },
    ],
    review: [
      {
        userId: "2",
        rating: 5,
        comment: "Super quiet neighborhood and smooth renting process.",
        created_at: "2023-03-05",
        updated_at: "2023-03-05",
      },
    ],
    propertyView: [
      {
        userId: "9",
        ip_address: "192.168.1.10",
        viewed_at: "2023-03-02",
      },
    ],
    status: "Available",
    created_at: "2023-02-20",
    updated_at: "2023-02-20",
  },
  {
    id: "3",
    title: "Spacious Family Villa",
    description: "Private 5-bedroom villa with a large garden, double garage, and high security.",
    property_type: "Villa",
    listing_type: "For Sale",
    price: 850000,
    bedrooms: 5,
    bathrooms: 4,
    area_sqft: 3800,
    agentName: "Htin Lin",
    propertyImage: [
      {
        url: "https://example.com/images/property3_1.jpg",
        alt: "Front Yard",
      },
      {
        url: "https://example.com/images/property3_2.jpg",
        alt: "Master Bedroom",
      },
    ],
    address: {
      street: "78 University Avenue",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11031",
      country: "Myanmar",
      latitude: 16.8285,
      longitude: 96.1552,
    },
    faviourite: [
      {
        userId: "7",
        created_at: "2023-03-15",
      },
      {
        userId: "11",
        created_at: "2023-03-18",
      },
    ],
    review: [],
    propertyView: [
      {
        userId: "11",
        ip_address: "192.168.1.15",
        viewed_at: "2023-03-16",
      },
    ],
    status: "Pending",
    created_at: "2023-03-01",
    updated_at: "2023-03-25",
  },
  {
    id: "4",
    title: "Cozy Studio Apartment",
    description: "Compact, fully furnished studio near business hubs and public transport.",
    property_type: "Studio",
    listing_type: "For Rent",
    price: 600,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 450,
    agentName: "Michael Chen",
    propertyImage: [
      {
        url: "https://example.com/images/property4_1.jpg",
        alt: "Studio Interior",
      },
    ],
    address: {
      street: "12 Anawrahta Road",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11181",
      country: "Myanmar",
      latitude: 16.7761,
      longitude: 96.1625,
    },
    faviourite: [],
    review: [
      {
        userId: "14",
        rating: 3,
        comment: "A bit small, but great value for the price location-wise.",
        created_at: "2023-04-02",
        updated_at: "2023-04-02",
      },
    ],
    propertyView: [
      {
        userId: "14",
        ip_address: "192.168.1.44",
        viewed_at: "2023-03-28",
      },
    ],
    status: "Rented",
    created_at: "2023-03-10",
    updated_at: "2023-04-01",
  },
  {
    id: "5",
    title: "Commercial Office Space",
    description: "Open-plan corporate office unit with dedicated parking and high-speed fiber internet.",
    property_type: "Commercial",
    listing_type: "For Rent",
    price: 3200,
    bedrooms: 0,
    bathrooms: 2,
    area_sqft: 2200,
    agentName: "Min Thant",
    propertyImage: [
      {
        url: "https://example.com/images/property5_1.jpg",
        alt: "Office Workspace",
      },
      {
        url: "https://example.com/images/property5_2.jpg",
        alt: "Conference Room",
      },
    ],
    address: {
      street: "504 Strand Road",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11171",
      country: "Myanmar",
      latitude: 16.7694,
      longitude: 96.1583,
    },
    faviourite: [
      {
        userId: "6",
        created_at: "2023-04-12",
      },
    ],
    review: [
      {
        userId: "6",
        rating: 5,
        comment: "Perfect corporate setup for our tech startup team.",
        created_at: "2023-04-18",
        updated_at: "2023-04-18",
      },
    ],
    propertyView: [
      {
        userId: "6",
        ip_address: "192.168.1.88",
        viewed_at: "2023-04-10",
      },
    ],
    status: "Available",
    created_at: "2023-04-05",
    updated_at: "2023-04-05",
  },
  {
    id: "6",
    title: "Riverside Townhouse",
    description: "Modern 3-story townhouse with private balcony overlooking the river corridor.",
    property_type: "Townhouse",
    listing_type: "For Sale",
    price: 420000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 2100,
    agentName: "Khin Khaing",
    propertyImage: [
      {
        url: "https://example.com/images/property6_1.jpg",
        alt: "Townhouse Front",
      },
      {
        url: "https://example.com/images/property6_2.jpg",
        alt: "Kitchen View",
      },
    ],
    address: {
      street: "89 Lower Kyeemyindaine Rd",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11101",
      country: "Myanmar",
      latitude: 16.7912,
      longitude: 96.1287,
    },
    faviourite: [
      {
        userId: "2",
        created_at: "2023-05-02",
      },
      {
        userId: "4",
        created_at: "2023-05-06",
      },
    ],
    review: [],
    propertyView: [
      {
        userId: "2",
        ip_address: "192.168.2.1",
        viewed_at: "2023-05-01",
      },
    ],
    status: "Available",
    created_at: "2023-04-20",
    updated_at: "2023-04-20",
  },
  {
    id: "7",
    title: "Mandalay Heritage House",
    description: "Classic teakwood property with expansive yard and traditional architectural detail.",
    property_type: "House",
    listing_type: "For Sale",
    price: 510000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 3100,
    agentName: "Kyaw Kyaw",
    propertyImage: [
      {
        url: "https://example.com/images/property7_1.jpg",
        alt: "Heritage Exterior",
      },
    ],
    address: {
      street: "26th Street, Chanayethazan",
      city: "Mandalay",
      state: "Mandalay Region",
      postal_code: "05011",
      country: "Myanmar",
      latitude: 21.975,
      longitude: 96.0836,
    },
    faviourite: [
      {
        userId: "9",
        created_at: "2023-05-20",
      },
    ],
    review: [
      {
        userId: "9",
        rating: 5,
        comment: "Beautiful woodwork and craftsmanship!",
        created_at: "2023-05-22",
        updated_at: "2023-05-22",
      },
    ],
    propertyView: [
      {
        userId: "9",
        ip_address: "192.168.2.14",
        viewed_at: "2023-05-19",
      },
    ],
    status: "Sold",
    created_at: "2023-05-01",
    updated_at: "2023-06-10",
  },
  {
    id: "8",
    title: "Penthouse with Shwedagon View",
    description: "Exclusive top-floor penthouse with panoramic sunset views and private rooftop terrace.",
    property_type: "Penthouse",
    listing_type: "For Sale",
    price: 1200000,
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 4500,
    agentName: "Aung Aung",
    propertyImage: [
      {
        url: "https://example.com/images/property8_1.jpg",
        alt: "Penthouse Terrace",
      },
      {
        url: "https://example.com/images/property8_2.jpg",
        alt: "Master Suite",
      },
    ],
    address: {
      street: "10 Shwe Gon Taing Rd",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11201",
      country: "Myanmar",
      latitude: 16.8083,
      longitude: 96.1558,
    },
    faviourite: [
      {
        userId: "2",
        created_at: "2023-06-01",
      },
      {
        userId: "7",
        created_at: "2023-06-03",
      },
      {
        userId: "11",
        created_at: "2023-06-12",
      },
    ],
    review: [
      {
        userId: "11",
        rating: 5,
        comment: "Unmatched skyline views in the city.",
        created_at: "2023-06-15",
        updated_at: "2023-06-15",
      },
    ],
    propertyView: [
      {
        userId: "2",
        ip_address: "192.168.1.1",
        viewed_at: "2023-05-29",
      },
    ],
    status: "Available",
    created_at: "2023-05-25",
    updated_at: "2023-05-25",
  },
  {
    id: "9",
    title: "High-Rise Studio in Bahahan",
    description: "Affordable contemporary studio with building gym, 24/7 security, and backup generator.",
    property_type: "Studio",
    listing_type: "For Rent",
    price: 750,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 520,
    agentName: "Htin Lin",
    propertyImage: [
      {
        url: "https://example.com/images/property9_1.jpg",
        alt: "Studio Open Layout",
      },
    ],
    address: {
      street: "105 Kabar Aye Pagoda Rd",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11202",
      country: "Myanmar",
      latitude: 16.8181,
      longitude: 96.1594,
    },
    faviourite: [],
    review: [],
    propertyView: [
      {
        userId: "14",
        ip_address: "192.168.3.11",
        viewed_at: "2023-06-18",
      },
    ],
    status: "Rented",
    created_at: "2023-06-10",
    updated_at: "2023-06-10",
  },
  {
    id: "10",
    title: "Suburban Family Bungalow",
    description: "Quiet 3-bedroom detached home featuring lush front lawn and private gated entry.",
    property_type: "Bungalow",
    listing_type: "For Sale",
    price: 290000,
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1800,
    agentName: "Khin Khaing",
    propertyImage: [
      {
        url: "https://example.com/images/property10_1.jpg",
        alt: "Bungalow Front View",
      },
      {
        url: "https://example.com/images/property10_2.jpg",
        alt: "Backyard Garden",
      },
    ],
    address: {
      street: "14 Parami Road",
      city: "Yangon",
      state: "Yangon Region",
      postal_code: "11091",
      country: "Myanmar",
      latitude: 16.8529,
      longitude: 96.1438,
    },
    faviourite: [
      {
        userId: "4",
        created_at: "2023-07-02",
      },
    ],
    review: [
      {
        userId: "4",
        rating: 4,
        comment: "Charming home in a peaceful neighborhood.",
        created_at: "2023-07-05",
        updated_at: "2023-07-05",
      },
    ],
    propertyView: [
      {
        userId: "4",
        ip_address: "192.168.1.90",
        viewed_at: "2023-07-01",
      },
    ],
    status: "Sold",
    created_at: "2023-06-25",
    updated_at: "2023-06-25",
  },
];

export const appointmentDummyData = [
  {
    id: "1",
    propertyName: "Luxury Apartment in Downtown",
    userName: "Zaw Zaw",
    appointmentDate: "2023-08-15",
    appointmentTime: "14:00",
    status: "Pending",
    created_at: "2023-08-01",
    updated_at: "2023-08-01",
  },
  {
    id: "2",
    propertyName: "Modern Condo Near Inya Lake",
    userName: "Thida Win",
    appointmentDate: "2023-08-20",
    appointmentTime: "10:00",
    status: "Confirmed",
    created_at: "2023-08-05",
    updated_at: "2023-08-05",
  },
  {
    id: "3",
    propertyName: "Spacious Family Villa",
    userName: "Mya Mya",
    appointmentDate: "2023-08-22",
    appointmentTime: "11:30",
    status: "Confirmed",
    created_at: "2023-08-08",
    updated_at: "2023-08-09",
  },
  {
    id: "4",
    propertyName: "Cozy Studio Apartment",
    userName: "Nanda Kyaw",
    appointmentDate: "2023-08-25",
    appointmentTime: "15:00",
    status: "Cancelled",
    created_at: "2023-08-10",
    updated_at: "2023-08-12",
  },
  {
    id: "5",
    propertyName: "Commercial Office Space",
    userName: "Su Su",
    appointmentDate: "2023-08-28",
    appointmentTime: "09:00",
    status: "Completed",
    created_at: "2023-08-11",
    updated_at: "2023-08-28",
  },
  {
    id: "6",
    propertyName: "Riverside Townhouse",
    userName: "Aye Aye Tint",
    appointmentDate: "2023-09-02",
    appointmentTime: "13:30",
    status: "Pending",
    created_at: "2023-08-15",
    updated_at: "2023-08-15",
  },
  {
    id: "7",
    propertyName: "Mandalay Heritage House",
    userName: "Zaw Zaw",
    appointmentDate: "2023-09-05",
    appointmentTime: "16:00",
    status: "Confirmed",
    created_at: "2023-08-18",
    updated_at: "2023-08-19",
  },
  {
    id: "8",
    propertyName: "Penthouse with Shwedagon View",
    userName: "Thida Win",
    appointmentDate: "2023-09-10",
    appointmentTime: "11:00",
    status: "Pending",
    created_at: "2023-08-20",
    updated_at: "2023-08-20",
  },
  {
    id: "9",
    propertyName: "High-Rise Studio in Bahahan",
    userName: "Nanda Kyaw",
    appointmentDate: "2023-09-12",
    appointmentTime: "10:30",
    status: "Completed",
    created_at: "2023-08-22",
    updated_at: "2023-09-12",
  },
  {
    id: "10",
    propertyName: "Suburban Family Bungalow",
    userName: "Aye Aye Tint",
    appointmentDate: "2023-09-15",
    appointmentTime: "14:30",
    status: "Cancelled",
    created_at: "2023-08-25",
    updated_at: "2023-08-27",
  },
];

export const transactionDummyData = [
  {
    id: "1",
    propertyName: "Luxury Apartment in Downtown",
    buyerName: "Zaw Zaw",
    agentName: "Aung Aung",
    amount: 350000,
    paymentStatus: "Pending",
    transactionDate: "2023-08-15",
    created_at: "2023-08-01",
    updated_at: "2023-08-01",
  },
  {
    id: "2",
    propertyName: "Modern Condo Near Inya Lake",
    buyerName: "Thida Win",
    agentName: "Kyaw Kyaw",
    amount: 1500,
    paymentStatus: "Paid",
    transactionDate: "2023-08-20",
    created_at: "2023-08-05",
    updated_at: "2023-08-20",
  },
  {
    id: "3",
    propertyName: "Spacious Family Villa",
    buyerName: "Mya Mya",
    agentName: "Htin Lin",
    amount: 850000,
    paymentStatus: "Paid",
    transactionDate: "2023-08-25",
    created_at: "2023-08-08",
    updated_at: "2023-08-25",
  },
  {
    id: "4",
    propertyName: "Cozy Studio Apartment",
    buyerName: "Nanda Kyaw",
    agentName: "Michael Chen",
    amount: 600,
    paymentStatus: "Failed",
    transactionDate: "2023-08-26",
    created_at: "2023-08-10",
    updated_at: "2023-08-26",
  },
  {
    id: "5",
    propertyName: "Commercial Office Space",
    buyerName: "Su Su",
    agentName: "Min Thant",
    amount: 3200,
    paymentStatus: "Paid",
    transactionDate: "2023-08-28",
    created_at: "2023-08-11",
    updated_at: "2023-08-28",
  },
  {
    id: "6",
    propertyName: "Riverside Townhouse",
    buyerName: "Aye Aye Tint",
    agentName: "Khin Khaing",
    amount: 420000,
    paymentStatus: "Pending",
    transactionDate: "2023-09-02",
    created_at: "2023-08-15",
    updated_at: "2023-08-15",
  },
  {
    id: "7",
    propertyName: "Mandalay Heritage House",
    buyerName: "Zaw Zaw",
    agentName: "Kyaw Kyaw",
    amount: 510000,
    paymentStatus: "Paid",
    transactionDate: "2023-09-06",
    created_at: "2023-08-18",
    updated_at: "2023-09-06",
  },
  {
    id: "8",
    propertyName: "Penthouse with Shwedagon View",
    buyerName: "Thida Win",
    agentName: "Aung Aung",
    amount: 1200000,
    paymentStatus: "Pending",
    transactionDate: "2023-09-11",
    created_at: "2023-08-20",
    updated_at: "2023-08-20",
  },
  {
    id: "9",
    propertyName: "High-Rise Studio in Bahahan",
    buyerName: "Nanda Kyaw",
    agentName: "Htin Lin",
    amount: 750,
    paymentStatus: "Paid",
    transactionDate: "2023-09-12",
    created_at: "2023-08-22",
    updated_at: "2023-09-12",
  },
  {
    id: "10",
    propertyName: "Suburban Family Bungalow",
    buyerName: "Aye Aye Tint",
    agentName: "Khin Khaing",
    amount: 290000,
    paymentStatus: "Refunded",
    transactionDate: "2023-09-16",
    created_at: "2023-08-25",
    updated_at: "2023-09-18",
  },
];